package org.bob.web.applications.mycash.engine.hc.dao;
// Generated 31-lug-2016 16.50.26 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private int id;
     private Serializable name;
     private String type;
     private double amount;
     private Date tmstIns;
     private Date tmstUpd;
     private Set transactionsesForToAcn = new HashSet(0);
     private Set transactionsesForFromAcn = new HashSet(0);

    public Accounts() {
    }

	
    public Accounts(int id, Serializable name, String type, double amount, Date tmstIns) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.amount = amount;
        this.tmstIns = tmstIns;
    }
    public Accounts(int id, Serializable name, String type, double amount, Date tmstIns, Date tmstUpd, Set transactionsesForToAcn, Set transactionsesForFromAcn) {
       this.id = id;
       this.name = name;
       this.type = type;
       this.amount = amount;
       this.tmstIns = tmstIns;
       this.tmstUpd = tmstUpd;
       this.transactionsesForToAcn = transactionsesForToAcn;
       this.transactionsesForFromAcn = transactionsesForFromAcn;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public Date getTmstIns() {
        return this.tmstIns;
    }
    
    public void setTmstIns(Date tmstIns) {
        this.tmstIns = tmstIns;
    }
    public Date getTmstUpd() {
        return this.tmstUpd;
    }
    
    public void setTmstUpd(Date tmstUpd) {
        this.tmstUpd = tmstUpd;
    }
    public Set getTransactionsesForToAcn() {
        return this.transactionsesForToAcn;
    }
    
    public void setTransactionsesForToAcn(Set transactionsesForToAcn) {
        this.transactionsesForToAcn = transactionsesForToAcn;
    }
    public Set getTransactionsesForFromAcn() {
        return this.transactionsesForFromAcn;
    }
    
    public void setTransactionsesForFromAcn(Set transactionsesForFromAcn) {
        this.transactionsesForFromAcn = transactionsesForFromAcn;
    }




}


