package org.bob.web.applications.mycash.engine.hc.dao;
// Generated 31-lug-2016 16.50.26 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Portfolios generated by hbm2java
 */
public class Portfolios  implements java.io.Serializable {


     private int id;
     private Users users;
     private Serializable name;
     private double amount;
     private Date tmstIns;
     private Date tmstUpd;

    public Portfolios() {
    }

	
    public Portfolios(int id, Serializable name, double amount, Date tmstIns, Date tmstUpd) {
        this.id = id;
        this.name = name;
        this.amount = amount;
        this.tmstIns = tmstIns;
        this.tmstUpd = tmstUpd;
    }
    public Portfolios(int id, Users users, Serializable name, double amount, Date tmstIns, Date tmstUpd) {
       this.id = id;
       this.users = users;
       this.name = name;
       this.amount = amount;
       this.tmstIns = tmstIns;
       this.tmstUpd = tmstUpd;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public Date getTmstIns() {
        return this.tmstIns;
    }
    
    public void setTmstIns(Date tmstIns) {
        this.tmstIns = tmstIns;
    }
    public Date getTmstUpd() {
        return this.tmstUpd;
    }
    
    public void setTmstUpd(Date tmstUpd) {
        this.tmstUpd = tmstUpd;
    }




}


